### ISSUE TITLE
Remove global CSS styles

### ISSUE THREAD

**Issue by theodorejb** [Baremetrics/calendar#15]
Right now there is a reset file (/dev/sass/vendor/_reset.scss) which overrides browser styling defaults. A custom font-family is also being set on the global body and html elements. This prevents us from easily using the date picker on our site, as we would have to manually override all these changes to the global environment.

Instead of modifying globals like this, could the font family instead be applied to the date picker classes, and the global CSS reset be removed in favor of only resetting styles on date picker specific classes? This would greatly improve the reusability value of this component.

**Comment by kalepail** [comment]
Removing the reset file is a really good idea, not sure why I didn't do that anyway. As for the font that whole `_home.scss` file is intended to be replaced with whatever you're using in your main app. You could and probably should modify the `_variables.scss` file to better match your current setup as I assume you won't Proxima Nova anyway. I will go ahead and put that variable into the `.daterange` class though.
