### ISSUE TITLE
Can't select custom range of one day

### ISSUE THREAD

**Issue by samuelreh** [Baremetrics/calendar#18]
I tried to select a range of just one day, but I can't seem to. Is this the expected behavior?

**Comment by kalepail** [comment]
Yes. For picking one day you should use the single date range picker option

**Comment by samuelreh** [comment]
Thanks for the quick response. My users need to be able to choose a day or many days. I'd rather just use one UI element, not toggle between them. Is there any particular reason for not wanting to support this use case?

**Comment by kalepail** [comment]
For our particular use case in Baremetrics a date range of the same day makes no sense. It wouldn't be very tough to modify the code to allow a range on one day though so feel free to just edit to suit your use case.

**Comment by dja** [comment]
I'd also +1 this, even as just a params option. :+1: 

update: nevermind, I don't know how I missed the new param for same_day_range
