### ISSUE TITLE
Internacionalization

### ISSUE THREAD

**Issue by MarcosBL** [Baremetrics/calendar#2]
Just as an enhancement, please provide the ability to get translations, maybe via external files

**Comment by olso** [comment]
just call it i18n next time :laughing:

**Comment by MarcosBL** [comment]
:+1: :smile:

**Comment by tzi** [comment]
:+1: For i18n

What need to be translated:
- Date format, ex "Jun 1, 2015"
- Range label, ex "Last month"
- Month name, ex "June"
- The starting day, countries start their week with monday 

Cheers,
Thomas.

**Comment by kalepail** [comment]
This would be a great addition! Thanks for the request. I'm gonna add the help wanted label for now and if any of y'all wanna submit a PR for it feel free.

**Comment by SleeplessByte** [comment]
Starting day is `moment` is `moment.firstDayOfWeek()`
