### ISSUE TITLE
callback function is not called if only start date is changed in Double Calendar

### ISSUE THREAD

**Issue by enekochan** [Baremetrics/calendar#25]
In a Double Calendar if you change the start date it is correctly updated and the calendar then expects you to select the end date. The issue appears when you don't want to change the end date and you just click outside the calendar: the callback function is not called and thus your code doesn't do it's business.

**Comment by scottrobertson** [comment]
This is similar to https://github.com/Baremetrics/calendar/pull/1

**Comment by kalepail** [comment]
@enekochan Should be good to go on this one.
https://github.com/Baremetrics/calendar/commit/c7e68c20f4a4b165be75958284296de00b0f30e4

**Comment by enekochan** [comment]
Thanks!
