### ISSUE TITLE
Shouldn't split on –

### ISSUE THREAD

**Issue by SleeplessByte** [Baremetrics/calendar#27]
It's not available in all fonts.

Rather use an `&ndash;` in the first place and annotate the two dates in separate elements. Also removes the need to translate the dash using css.

**Comment by kalepail** [comment]
https://github.com/Baremetrics/calendar/commit/3c4b5bc16c8ee67e95ab6fb5ccc502400a34fda5

**Comment by SleeplessByte** [comment]
Well, you're still splitting on that character, so didn't this break the calendar?

**Comment by kalepail** [comment]
What do you mean "splitting"? Not quite sure what you're referring to.

**Comment by SleeplessByte** [comment]
Nvm, you didn't change the presets, which wouldn't work because of [Calendar.js#L43](https://github.com/Baremetrics/calendar/blob/3c4b5bc16c8ee67e95ab6fb5ccc502400a34fda5/dev/js/Calendar.js#L43). :)
