### ISSUE TITLE
Should not call new Date

### ISSUE THREAD

**Issue by SleeplessByte** [Baremetrics/calendar#28]
The whole point of moment is that it normalizes `new Date()` calls. Instead replace the calls with `moment()`. All operations should be `moment` operations.

For example `new Date('January 1, 1900')` becomes `moment( [1900, 1, 1] )` or `moment( '1900-01-01', 'YYYY-MM-DD')`;

**Comment by kalepail** [comment]
Mm unfortunately this would place limitations on the date formats you could use when instantiating the calendar or entering dates but I could and will do better on not using new Date when I don't need to.

**Comment by kalepail** [comment]
https://github.com/Baremetrics/calendar/commit/ef9bd8cedca66ffb268f6776a2820d46995ba03a

**Comment by kalepail** [comment]
On second thought I think I'd like to limit the date input to that format for consistency's sake.
https://github.com/Baremetrics/calendar/commit/22e0256e0b76d6f49085eb59ee1b20474ef29e55

**Comment by SleeplessByte** [comment]
You should probably limit to a format, not necc. that format, with regards to #26 #2

**Comment by kalepail** [comment]
Opening this back up.. I didn't like my implementation. It works for me as is but if someone wants to knock it out that's fine by me.

**Comment by SleeplessByte** [comment]
I'll look into it :)
