### ISSUE TITLE
Up/down keyboard support

### ISSUE THREAD

**Issue by kalenjordan** [Baremetrics/calendar#3]
Wow - this date picker is vurr' nice.  You guys are amazing.

I was thinking maybe one thing that would be nice is when the keybord cursor is over the day of the month, let's say, and if you press up/down on the keyboard if that could nudge the number down/up that might be cool.

Samesies for month/year too.

**Comment by kalepail** [comment]
I'm planning on adding some similar functionality to the way the mac Calendar and apps like Fantastical do it, with up/down shifting days and left/right shifting months. You're mouse will already be in hand to open the calendar but some keyboard support would be nice.

**Comment by kalepail** [comment]
Added some basic keyboard support in the [latest commit](https://github.com/Baremetrics/calendar/commit/e2fdc8c9e4a3348fdda0d36fd24402c5ca63f524)

Once you click a date to open the calendar..
- day = keystroke up/down
- week = hold shift + keystroke up/down
- month = hold meta + keystroke up/down
