### ISSUE TITLE
Locale/option based first day of the week

### ISSUE THREAD

**Issue by enekochan** [Baremetrics/calendar#32]
Right now the first day of the week is set to Sunday as it is used in en_US. But lots of languages, spanish for example, use other day, usually Monday, as first day of the week. We already have text and dates translations/localization which is great but this new feature I think should be a must.

I've tried myself coding this feature but failed. The only thing I've managed to change is the order of the days array (S, M, T, ...) based on `moment().localeData().firstDayOfWeek()` replacing this code in `Calendar.prototype.calendarHTML`:

```
$.each(this.days_array || moment.weekdaysMin(), function(i, elem) {
  ul_days_of_the_week.append('<li class="dr-day-of-week">' + elem + '</li>'); 
});
```

With this code:

```
var days = this.days_array || moment.weekdaysMin();
days = days.splice(moment().localeData().firstDayOfWeek()).concat(days.splice(0, moment().localeData().firstDayOfWeek()));
$.each(days, function(i, elem) {
  ul_days_of_the_week.append('<li class="dr-day-of-week">' + elem + '</li>'); 
});
```

**Comment by cissav** [comment]
Any news on this one?

**Comment by kalepail** [comment]
No not yet as we don't currently need this for Baremetrics. I also haven't heard much from other people needing this feature. I don't think it'd be _super_ hard to do but it'd take some time to think through the best way. You'd definitely want it to be an option, though maybe a function option that doesn't automatically do anything until you explicitly tell it which day of the week it should start the week on.

**Comment by kalepail** [comment]
Added in https://github.com/Baremetrics/calendar/releases/tag/v1.0.6
