### ISSUE TITLE
Standalone css file

### ISSUE THREAD

**Issue by kalenjordan** [Baremetrics/calendar#36]
Hey guys, amazing work on this!  I just pulled it into my app and needed to fidget with the css a little bit in order to remove some of the non-daterange styles (body, h1, etc.).  Would it make sense to break some of those things out of the css file?  

Let me know if you'd like me to PR the CSS file that I scrubbed.

Thanks again!

**Comment by kalepail** [comment]
It is broken out in the Sass source.. but it might be helpful to actually generate a sort of vendor css file separate from the actual name spaced calendar stuff.

**Comment by kalenjordan** [comment]
Ah.  Duh!  My bad.
