### ISSUE TITLE
Add ability to set placeholder text for single dates

### ISSUE THREAD

**Issue by aperkins81** [Baremetrics/calendar#39]
Thanks for the great date picker!

Just one nit-pick.

The placeholder text for single dates serves little purpose for the lay-user who is most likely to use the GUI instead of typing in a date.

Also, placeholder text such as Do MMMM YYYY looks a little ugly (and possibly confusing) - it would be nice to be able to overwrite this value, for example, to match other inputs' placeholder values.

Cheers

**Comment by kalepail** [comment]
Added in https://github.com/Baremetrics/calendar/releases/tag/v1.0.6
