### ISSUE TITLE
Baremetrics Calendar Install 

### ISSUE THREAD

**Issue by mtmcfarl** [Baremetrics/calendar#56]
I'm having a hard time getting the open source calendar working in my application. It says moment and Calendar is undefined. I installed moment via `npm install moment --save` and I copied and pasted Calendar.js into my Rails project. Anything pop up recently about the calendar not working?

**Comment by kalepail** [comment]
Sounds like you're trying to use the calendar before it's been installed. NPM installs also don't give you access to moment out of the box. You'll still need to call their script in the `<head>` or as a `require()` function. This isn't a calendar issue though.
