### ISSUE TITLE
Request: Week starts on…

### ISSUE THREAD

**Issue by Robert-Black** [Baremetrics/calendar#58]
In Australia, calendars normally start the week on a Monday instead of Sunday. I'd guess this is a problem in other countries.

It would be mildly helpful if there was an option in the settings for the picker to "Start week on… [pick a day]"

**Comment by kalepail** [comment]
See https://github.com/Baremetrics/calendar/pull/53 
If you could fork and test that branch and confirm whether or not it works, that'd be awesome!
