### ISSUE TITLE
When 'required' is set to 'false' the input field always initializes to blank

### ISSUE THREAD

**Issue by jagthedrummer** [Baremetrics/calendar#63]
When I pass in a value for `current_date` but also set `required` to be `false` I'm ending up with a date picker that has the initial value set to '', which lets the `placeholder` show up. I think it should set the initial value to be the formatted version of `current_date`.

I think this line is the culprit.

https://github.com/Baremetrics/calendar/blob/master/dev/js/Calendar.js#L776

**Comment by kalepail** [comment]
524c55b363c2e0e56d7b3ba6be485dc3c043ac7d
