### ISSUE TITLE
"This month" added to custom presets

### ISSUE THREAD

**Issue by tiljanssen** [Baremetrics/calendar#65]
"This month" is added to custom presets when the month is older than a few days.

This functionality should probably be limited to the default presets, not for custom presets

**Comment by kalepail** [comment]
Oops! Good point.
I'll get to this asap. Feel free to submit a PR if it's urgent though

**Comment by kalepail** [comment]
54a3d2303952d01ccb27b6c7075e89017809a8b8

**Comment by ianmooney** [comment]
Hi @tyvdh, it looks like the latest release available on npm is 1.0.8. I'd love to get this fix into our app. Would you be able to publish the newer releases on npm?

**Comment by kalepail** [comment]
@ianmooney Done.

**Comment by ianmooney** [comment]
Awesome, thanks a lot.
