### ISSUE TITLE
Strange default presets if latest-date != current-date

### ISSUE THREAD

**Issue by tiljanssen** [Baremetrics/calendar#66]
The default presets are relative to the latest-date, but the names relate to the current date ("this month").

Proposed solution:
Define the presets relative to the current date, then limit them to the allowed range, and then include them if they have "enough length"

(or do not specify default presets at all).

**Comment by kalepail** [comment]
@tiljanssen I see the dilemma here but I think it's outlier enough that you could use either your own custom presets or just set `presets: false` on your own.
