### ISSUE TITLE
How to catch event when value is removed (emptied) for single calendar?

### ISSUE THREAD

**Issue by darklow** [Baremetrics/calendar#68]
Now callback event is being fired only when value is set for single calendar.
How to catch change event when value is deleted?
Thank you.

**Comment by kalepail** [comment]
Hmm good question. I'll have to take a look at that.

**Comment by kalepail** [comment]
33e4aafae134eb26f6be99a8854d57c44f2abcfd

**Comment by straube** [comment]
@tyvdh it seems like the `current_date` has a value – the latest selected date – even when I empty the calendar. I took a look at the available properties and at 33e4aaf but I couldn't find anything that can tell me there is no date selected. Am I missing something?

Thanks! :)

**Comment by kalepail** [comment]
@straube That's true. This is due to some restrictions within the code itself needing to keep some reference of a date. You can however use `this.selected.innerText` inside the callback to determine if there is a value currently selected.

**Comment by straube** [comment]
@tyvdh just gave it a try and it worked! :tada:
