### ISSUE TITLE
MouseEvent.path() only supported in Chrome

### ISSUE THREAD

**Issue by laynegt** [Baremetrics/calendar#75]
in v.1.0.10, https://github.com/Baremetrics/calendar/blob/master/dev/js/Calendar.js#L189 uses `MouseEvent.path()`, which appears to be only supported by Chrome.  Ran into problems in our test suite with phantom.

Thanks for the calendar picker, love it.

**Comment by kalepail** [comment]
Ah whoops! Will take a look and fix asap. Or feel free to submit a PR fix
