### ISSUE TITLE
Double Date Range error when date range is same day

### ISSUE THREAD

**Issue by dja** [Baremetrics/calendar#8]
Looks like the start date and end date are compared based on their html text value, which is formatted as Month Day, Year. It would be beneficial if it were based on actual Moment(), whether in unix or date. The main reason is that it causes complications when the start date and end date are both the same day (but may want that to be hours/min etc).

**Comment by kalepail** [comment]
I actually do do a date comparison off the html values.. so the html values are converted into a date object. Anything beyond just days though is beyond the scope of this particular date range but if you'd like to add hour/min functionality I'd be glad to at least make it a separate branch if no include it into the main branch.
