### ISSUE TITLE
cdnjs hosting

### ISSUE THREAD

**Issue by sashberd** [Baremetrics/calendar#83]
Hi @tyvdh,
We would like to [add ](https://github.com/cdnjs/cdnjs/issues/10551)you library to cdnjs hosting
Which files we should host?
Thanks

**Comment by kalepail** [comment]
- https://github.com/Baremetrics/calendar/blob/master/public/js/Calendar.js
- https://github.com/Baremetrics/calendar/blob/master/public/css/application.css
