### ISSUE TITLE
f.path is undefined in Firefox

### ISSUE THREAD

**Issue by gerdus** [Baremetrics/calendar#87]
In Firefox(60) clicking outside the calendar gives following error in console and does not close it:
`f.path is undefined` 
error on this line (Calendar.js line 189)
`var contains = self.element.find(f.path[0]);`

event.path is non-standard; standard seems to be event.composedPath()
Fixed it locally with:
`var path = f.path || (f.composedPath && f.composedPath()) || [f.target.parentNode,];`
`var contains = self.element.find(path[0]);`
Edge does not support either so faked a path with event.target.

**Comment by leonardofaria** [comment]
@gerdus I am having the same issue and I found another way to fix it.

I am trying to test what you did locally could you please detail a bit more?

**Comment by gerdus** [comment]
Looking at it again looks like this was fixed in 1.0.12 (latest on NPM is still v1.0.11)
in 1.0.11 the line was
var contains = self.element.find(f.path[0]);
