### ISSUE TITLE
Integration with Vue.js

### ISSUE THREAD

**Issue by silent-lad** [Baremetrics/calendar#98]
Can I know how can I integrate this inside a Vue.js Application?

**Comment by kalepail** [comment]
I mean just like you would include it in any other project. You'll want to create the calendar inside the VueJS component and you'll need to watch that if you remove the element you recreate the calendar when you replace it back in to the DOM. But other than that there really isn't anything special for using this in a framework like VueJS. If you understand how shadow DOM frameworks work it will help when using DOM dependent plugins like this.

**Comment by kalepail** [comment]
Fwiw we do this all the time in Baremetrics actually. We include a call to the calendar script in the head and then just call the `new Calendar` whenever we need to build a calendar.

**Comment by silent-lad** [comment]
> I mean just like you would include it in any other project. You'll want to create the calendar inside the VueJS component and you'll need to watch that if you remove the element you recreate the calendar when you replace it back in to the DOM. But other than that there really isn't anything special for using this in a framework like VueJS. If you understand how shadow DOM frameworks work it will help when using DOM dependent plugins like this.


I kind of figured out this is what I had to do. But I'm a newbie here and I'm unable to implement this. Can you give me a heads up in the form of a simple github gist or anything? I will be really glad. Thanks in advance. Thanks for such an awesome package though :)
